language: node_js
node_js: stable

install: true

branches:
  only:
    - master

before_script:
  - git config --global user.name "yudan"
  - git config --global user.email "yudan@gaoding.com"

script:
  - git push -f https://$GITHUB_KEY@github.com/$TRAVIS_REPO_SLUG.git `npm version patch -m "%s [ci skip]"`
  - git push -f https://$GITHUB_KEY@github.com/$TRAVIS_REPO_SLUG.git HEAD:master